import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';
import {defineConfig, Plugin} from 'vite';

function syncContentPlugin(): Plugin {
  return {
    name: 'sync-content-server',
    configureServer(server) {
      server.middlewares.use('/api/sync-content', (req, res) => {
        if (req.method === 'POST') {
          let body = '';
          req.on('data', (chunk) => {
            body += chunk;
          });
          req.on('end', () => {
            try {
              const data = JSON.parse(body);
              const dir = import.meta.dirname || '.';
              const tsFilePath = path.resolve(dir, 'src/data/persistedContent.ts');
              const jsonFilePath = path.resolve(dir, 'src/data/persistedContent.json');

              const fileContent = `// Auto-generated by preview sync - used for production deployment on Vercel\nexport const persistedData: {\n  projects?: any[];\n  aboutContent?: any;\n  contactContent?: any;\n  lastUpdated?: string;\n} = ${JSON.stringify(data, null, 2)};\n`;

              fs.writeFileSync(tsFilePath, fileContent, 'utf-8');
              fs.writeFileSync(jsonFilePath, JSON.stringify(data, null, 2), 'utf-8');

              console.log('[sync-content] Successfully saved portfolio data to src/data/persistedContent.ts');
              res.setHeader('Content-Type', 'application/json');
              res.statusCode = 200;
              res.end(JSON.stringify({ success: true, timestamp: new Date().toISOString() }));
            } catch (err) {
              console.error('[sync-content] Error saving data:', err);
              res.setHeader('Content-Type', 'application/json');
              res.statusCode = 500;
              res.end(JSON.stringify({ error: String(err) }));
            }
          });
        } else if (req.method === 'GET') {
          const dir = import.meta.dirname || '.';
          const tsFilePath = path.resolve(dir, 'src/data/persistedContent.ts');
          const exists = fs.existsSync(tsFilePath);
          res.setHeader('Content-Type', 'application/json');
          res.statusCode = 200;
          res.end(JSON.stringify({ exists }));
        } else {
          res.statusCode = 405;
          res.end('Method Not Allowed');
        }
      });
    },
  };
}

export default defineConfig(() => {
  return {
    plugins: [react(), tailwindcss(), syncContentPlugin()],
    resolve: {
      alias: {
        '@': path.resolve(import.meta.dirname || '.'),
      },
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      // Do not modifyâfile watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
      // Disable file watching when DISABLE_HMR is true to save CPU during agent edits.
      watch: process.env.DISABLE_HMR === 'true' ? null : {},
    },
  };
});
