// Auto-generated by preview sync - used for production deployment on Vercel
export const persistedData: {
  projects?: any[];
  aboutContent?: any;
  contactContent?: any;
  lastUpdated?: string;
} = {};
